### ISSUE TITLE
最新版0.41.03 dashboard和yacd面板都打不开

### ISSUE THREAD

**Issue by ForestL18** [vernesong/OpenClash#1014]
新开一个issue，提示一下最新版的openclash的dashboard和yacd面板依然都打不开。新加的ruby，ruby-yaml依赖已添加，确定没有问题。问题还是配置文件里所必需的配置代码不能自动补全，导致检查可以通过，启动可以成功，但是外部控制面板打不开。

必要的配置：（原本为openclash自动添加）
port: 7890
socks-port: 7891
allow-lan: true
bind-address: ""
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
interface-name: eth0
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
dns:
listen: 127.0.0.1:7874
enable: true
ipv6: false
enhanced-mode: fake-ip
fake-ip-range: 198.18.0.1/16
fake-ip-filter:
##Custom fake-ip-filter##
- '.lan'
- 'time.windows.com'
- 'time.nist.gov'
- 'time.apple.com'
- 'time.asia.apple.com'
- '.ntp.org.cn'
- '.openwrt.pool.ntp.org'
- 'time1.cloud.tencent.com'
- 'time.ustc.edu.cn'
- 'pool.ntp.org'
- 'ntp.ubuntu.com'
- 'ntp.aliyun.com'
- 'ntp1.aliyun.com'
- 'ntp2.aliyun.com'
- 'ntp3.aliyun.com'
- 'ntp4.aliyun.com'
- 'ntp5.aliyun.com'
- 'ntp6.aliyun.com'
- 'ntp7.aliyun.com'
- 'time1.aliyun.com'
- 'time2.aliyun.com'
- 'time3.aliyun.com'
- 'time4.aliyun.com'
- 'time5.aliyun.com'
- 'time6.aliyun.com'
- 'time7.aliyun.com'
- '.time.edu.cn'
- 'time1.apple.com'
- 'time2.apple.com'
- 'time3.apple.com'
- 'time4.apple.com'
- 'time5.apple.com'
- 'time6.apple.com'
- 'time7.apple.com'
- 'time1.google.com'
- 'time2.google.com'
- 'time3.google.com'
- 'time4.google.com'
- 'music.163.com'
- '.music.163.com'
- '.126.net'
- 'musicapi.taihe.com'
- 'music.taihe.com'
- 'songsearch.kugou.com'
- 'trackercdn.kugou.com'
- '.kuwo.cn'
- 'api-jooxtt.sanook.com'
- 'api.joox.com'
- 'joox.com'
- 'y.qq.com'
- '.y.qq.com'
- 'streamoc.music.tc.qq.com'
- 'mobileoc.music.tc.qq.com'
- 'isure.stream.qqmusic.qq.com'
- 'dl.stream.qqmusic.qq.com'
- 'aqqmusic.tc.qq.com'
- 'amobile.music.tc.qq.com'
- '.xiami.com'
- '.music.migu.cn'
- 'music.migu.cn'
- '.msftconnecttest.com'
- '.msftncsi.com'
- 'localhost.ptlogin2.qq.com'
- '+.srv.nintendo.net'
- '+.stun.playstation.net'
- 'xbox..microsoft.com'
- '+.xboxlive.com'
- 'proxy.golang.org'
- 'stun..'
- 'stun...'
- 'heartbeat.belkin.com'
- '.linksys.com'
- '*.linksyssmartwifi.com'
##Custom fake-ip-filter END##
nameserver:
##Custom DNS##
- 114.114.114.114
- 119.29.29.29
- 119.28.28.28
- 223.5.5.5
- https://doh.rixcloud.dev/dns-query
fallback:
- https://cloudflare-dns.com/dns-query
- https://dns.google/dns-query
- tls://dns.google:853
- https://1.1.1.1/dns-query
- tls://1.1.1.1:853
- tls://8.8.8.8:853
fallback-filter:
geoip: true
ipcidr:
- 0.0.0.0/8
- 10.0.0.0/8
- 100.64.0.0/10
- 127.0.0.0/8
- 169.254.0.0/16
- 172.16.0.0/12
- 192.0.0.0/24
- 192.0.2.0/24
- 192.88.99.0/24
- 192.168.0.0/16
- 198.18.0.0/15
- 198.51.100.0/24
- 203.0.113.0/24
- 224.0.0.0/4
- 240.0.0.0/4
- 255.255.255.255/32
#===================== OpenClash-General-Settings =====================#

**Comment by vernesong** [comment]
```
ruby -ryaml -E UTF-8 -e "Value = YAML.load_file('path'); puts Value"
```
path换成配置文件路径看报错没

**Comment by jimmylucky** [comment]
我也有一样的问题，运行了命令没有报错

**Comment by vernesong** [comment]
> 我也有一样的问题，运行了命令没有报错

tg联系我

**Comment by InoruYang** [comment]
我退到v0.40.15-beta 终于能用了

**Comment by liaobadadi** [comment]
0.41.02 版本 同样问题， Yacd 控制面板	 ，Dashboard 控制面板	，全部打不开 ，安装上之后，百度都打不开，完全不能上网

**Comment by vernesong** [comment]
02版本处理大文件有问题，03版本在我这用acl一万行的规则测试是没问题的

**Comment by OleStore** [comment]
马上DD安装测试下，开工刷机

> 02版本处理大文件有问题，03版本在我这用acl一万行的规则测试是没问题的

**Comment by OleStore** [comment]
> 02版本处理大文件有问题，03版本在我这用acl一万行的规则测试是没问题的

2020-11-22 15:00:51 Warning: Multiple Stop Scripts Running, Exit...

**Comment by OleStore** [comment]
> 02版本处理大文件有问题，03版本在我这用acl一万行的规则测试是没问题的

修改了config.yaml文件权限755，启动成功
/etc/openclash/config
2020-11-22 15:04:57 History:【config.yaml】 Update Successful
2020-11-22 15:04:45 OpenClash Start Successful
2020-11-22 15:04:57 History:【config.yaml】 Restore Faild
2020-11-22 15:04:54 level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Disney Plus"
2020-11-22 15:04:54 level=info msg="Start initial rule provider PayPal"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Special"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Youku"
2020-11-22 15:04:54 level=info msg="Start initial rule provider JOOX"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Speedtest"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Tencent Video"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Line TV"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Apple TV"
2020-11-22 15:04:54 level=info msg="Start initial rule provider YouTube"
2020-11-22 15:04:54 level=info msg="Start initial rule provider iQiyi"
2020-11-22 15:04:54 level=info msg="Start initial rule provider PROXY"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Letv"
2020-11-22 15:04:54 level=info msg="Start initial rule provider encoreTVB"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Hulu Japan"
2020-11-22 15:04:54 level=info msg="Start initial rule provider ABC"
2020-11-22 15:04:54 level=info msg="Start initial rule provider KKTV"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Domestic"
2020-11-22 15:04:54 level=info msg="Start initial rule provider KKBOX"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Abema TV"
2020-11-22 15:04:54 level=info msg="Start initial rule provider Bahamut"
2020-11-22 15:04:54 level=info msg="Start initial rule provider PBS"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Reject"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Steam"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Apple News"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Microsoft"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Pornhub"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Bilibili"
2020-11-22 15:04:53 level=info msg="Start initial rule provider DAZN"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Apple"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Soundcloud"
2020-11-22 15:04:53 level=info msg="Start initial rule provider myTV SUPER"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Hulu"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Japonx"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Domestic IPs"
2020-11-22 15:04:53 level=info msg="Start initial rule provider HBO"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Netflix"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Fox Now"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Fox+"
2020-11-22 15:04:53 level=info msg="Start initial rule provider BBC iPlayer"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Amazon"
2020-11-22 15:04:53 level=info msg="Start initial rule provider ViuTV"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Pandora"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Spotify"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Netease Music"
2020-11-22 15:04:53 level=info msg="Start initial rule provider Telegram"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Proxy"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider PayPal"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Telegram"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Domestic"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Apple"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Steam"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Speedtest"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Spotify"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Youtube"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Netflix"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider AsianTV"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider AdBlock"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Auto - UrlTest"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Microsoft"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider Others"
2020-11-22 15:04:53 level=info msg="Start initial compatible provider GlobalTV"
2020-11-22 15:03:36 Warning: Multiple Stop Scripts Running, Exit...
2020-11-22 15:03:10 Warning: Multiple Stop Scripts Running, Exit...
2020-11-22 15:02:16 Warning: Multiple Stop Scripts Running, Exit...
2020-11-22 15:02:02 Config 【config】 Update Successful
2020-11-22 15:01:16 Warning: Multiple Stop Scripts Running, Exit...
2020-11-22 15:00:51 Warning: Multiple Stop Scripts Running, Exit...

**Comment by jimmylucky** [comment]
TUN模式启动成功，但是日志里还是有报错
=====================================
2020-11-22 15:34:05 level=info msg="[TCP] 192.168.0.176:57990 --> mail.google.com match RuleSet(PROXY) using Proxy"
2020-11-22 15:34:05 level=info msg="[TCP] 192.168.0.176:57991 --> mail.google.com match RuleSet(PROXY) using Proxy"
2020-11-22 15:33:54 level=info msg="[TCP] 192.168.0.176:57982 --> api.twitter.com match RuleSet(PROXY) using Proxy"
2020-11-22 15:33:54 level=info msg="[TCP] 192.168.0.176:57984 --> api.twitter.com match RuleSet(PROXY) using Proxy"
2020-11-22 15:33:44 History:【config.yaml】 Update Faild
2020-11-22 15:33:33 OpenClash Start Successful
2020-11-22 15:33:43 History:【config.yaml】 Restore Faild
====================================



redir-port模式启动失败
=====================
2020-11-22 15:32:54 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File
2020-11-22 15:32:54 Error: Get DNS 'enhanced-mode' Option Error, OpenClash Can Not Start With Raw Config File
2020-11-22 15:32:54 Error: Get DNS 'listen' Option Error, OpenClash Can Not Start With Raw Config File
2020-11-22 15:32:54 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
2020-11-22 15:33:05 level=fatal msg="Parse config error: yaml: unmarshal errors:\n  line 666: cannot unmarshal !!map into []string"
2020-11-22 15:32:54 Error: OpenClash Can Not Start, Try Use Backup Rules Start Again
2020-11-22 15:33:01 level=fatal msg="Parse config error: rules[3] [RULE-SET,Reject,AdBlock] error: unsupported rule type RULE-SET"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Auto - UrlTest"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Microsoft"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider AdBlock"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider AsianTV"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Spotify"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Domestic"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Others"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Steam"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider PayPal"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Apple"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Speedtest"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider GlobalTV"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Proxy"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Netflix"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider YouTube"
2020-11-22 15:33:01 level=info msg="Start initial compatible provider Telegram"
2020-11-22 15:32:05 Config 【config】 Update Successful

**Comment by vernesong** [comment]
@jimmylucky history是还原节点选择的步骤，内核没准备好的情况下有几率失败

**Comment by jimmylucky** [comment]
> @jimmylucky history是还原节点选择的步骤，内核没准备好的情况下有几率失败

但我现在每刷新下网页都会日志里出现失败，网页就卡住几秒等待着这个fail的几秒钟。。。

**Comment by vernesong** [comment]
> > @jimmylucky history是还原节点选择的步骤，内核没准备好的情况下有几率失败
> 
> 
> 
> 但我现在每刷新下网页都会日志里出现失败，网页就卡住几秒等待着这个fail的几秒钟。。。

启动配置文件有没有正确修改了控制面板的端口，不然无法还原会有等待重试的过程

**Comment by ForestL18** [comment]
> ```
> ruby -ryaml -E UTF-8 -e "Value = YAML.load_file('path'); puts Value"
> ```
> 
> path换成配置文件路径看报错没

我已经回退到v0.40.15-beta了，那就麻烦那位遇到同样问题兄弟帮你排除这个bug吧。辛苦了

**Comment by InoruYang** [comment]
> 我退到v0.40.15-beta 终于能用了

一开始是0.41.02（这个版本没什么问题），出了0.41.03后就安装了新版，然后国内外网都gg来，然后我有重装了0.41.02版，也不行了。只好退个大版本（ok了）。0.41.03版本不知怎么回事，首页加载特别慢，0.41.02不是太明显。

**Comment by jimmylucky** [comment]
升级到41.04上没问题了。

**Comment by frank2002** [comment]
> ```
> ruby -ryaml -E UTF-8 -e "Value = YAML.load_file('path'); puts Value"
> ```
> 
> path换成配置文件路径看报错没

我也有相同的问题，并且运行这个命令之后报错了，请问该如何解决？

```
/# ruby -ryaml -E UTF-8 -e "Value = YAML.load_file('path'); puts Value"
Traceback (most recent call last):
        3: from -e:1:in `<main>'
        2: from /usr/lib/ruby/2.7/psych.rb:577:in `load_file'
        1: from /usr/lib/ruby/2.7/psych.rb:577:in `open'
/usr/lib/ruby/2.7/psych.rb:577:in `initialize': No such file or directory @ rb_sysopen - path (Errno::ENOENT)
```

**Comment by dqh668** [comment]
openclash[v0.45.112-beta]无法打开dashboard和yacd面板

**Comment by jacobin** [comment]
openclash[v0.45.141-beta]无法打开dashboard和yacd面板

**Comment by Lumny-K** [comment]
> openclash[v0.45.141-beta]无法打开dashboard和yacd面板

我用的是Chrome。
我是openclash[v0.45.129-beta]
在外部控制中把两个控制台切换为meta版。

![Screenshot 2024-02-18 234933](https://github.com/vernesong/OpenClash/assets/125168545/c691a4ac-dfe7-45ed-976d-e4d095733034)

如果启动失败就是缺少meta内核。这里有完整的[meta](https://github.com/vernesong/OpenClash/tree/core/master/meta)内核
如果提示配置服务失败，启用默认服务就是缺少[dev](https://github.com/vernesong/OpenClash/tree/core/master/dev)内核
openclash文件夹:/etc/openclash/core，压缩包内默认clash，根据对应内核改名。

>如：clash_meta. 
dev内核默认clash

或者直接用配置管理传上去也行

之后就可以正常打开了
日志中会有一个ipv6的警告，有人说是ipv6地址占用了ipv4的，不过我这里没有发现。
>ps: arm64=armv8

![Screenshot 2024-02-18 235559](https://github.com/vernesong/OpenClash/assets/125168545/fa4577e0-335b-4f30-94d4-55e8c315effc)
![Screenshot 2024-02-19 000103](https://github.com/vernesong/OpenClash/assets/125168545/6e019bdc-ce09-4d59-b302-660420b06aac)
![Screenshot 2024-02-19 000316](https://github.com/vernesong/OpenClash/assets/125168545/60b179cb-24da-4465-9ed6-dd6e6f6af803)

**Comment by jacobin** [comment]
> > @jacobin openclash[v0.45.141-beta]无法打开dashboard和yacd面板
> 
> 我用的是Chrome。 我是openclash[v0.45.129-beta] 在外部控制中把两个控制台切换为meta版。
> 
> ![Screenshot 2024-02-18 234933](https://private-user-images.githubusercontent.com/125168545/305728195-c691a4ac-dfe7-45ed-976d-e4d095733034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjI5NzcsIm5iZiI6MTcxNDk2MjY3NywicGF0aCI6Ii8xMjUxNjg1NDUvMzA1NzI4MTk1LWM2OTFhNGFjLWRmZTctNDVlZC05NzZkLWU0ZDA5NTczMzAzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwMjMxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTBlOTc5MDZiMTBjMGFmYWFhODdkNjQ2Mjg2Mjg3NGI0MjhmZTZkNjc2ZTdhODU2YzY2MzA4ZmZjOTg4OWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NQqGfag_LfgYhDQfdW0vl_shOjJFke24dAo26wRr57k)
> 
> 如果启动失败就是缺少meta内核。这里有完整的[meta](https://github.com/vernesong/OpenClash/tree/core/master/meta)内核 如果提示配置服务失败，启用默认服务就是缺少[dev](https://github.com/vernesong/OpenClash/tree/core/master/dev)内核 openclash文件夹:/etc/openclash/core，压缩包内默认clash，根据对应内核改名。
> 
> > 如：clash_meta.
> > dev内核默认clash
> 
> 或者直接用配置管理传上去也行
> 
> 之后就可以正常打开了 日志中会有一个ipv6的警告，有人说是ipv6地址占用了ipv4的，不过我这里没有发现。
> 
> > ps: arm64=armv8
> 
> ![Screenshot 2024-02-18 235559](https://private-user-images.githubusercontent.com/125168545/305728625-fa4577e0-335b-4f30-94d4-55e8c315effc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjI5NzcsIm5iZiI6MTcxNDk2MjY3NywicGF0aCI6Ii8xMjUxNjg1NDUvMzA1NzI4NjI1LWZhNDU3N2UwLTMzNWItNGYzMC05NGQ0LTU1ZThjMzE1ZWZmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwMjMxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTA4Zjc0MDRjOWE3ODhhOGIzZDVlOThmMWQ2OWExODZkNTM0ZGQzY2NiZGUwOWU3YWQyZDVhNWIwOTBiNmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P_nlX9FvvMcLOqB6RLM6v-lEXvlVe-IsqW1-uZ7u3DU) ![Screenshot 2024-02-19 000103](https://private-user-images.githubusercontent.com/125168545/305728992-6e019bdc-ce09-4d59-b302-660420b06aac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjI5NzcsIm5iZiI6MTcxNDk2MjY3NywicGF0aCI6Ii8xMjUxNjg1NDUvMzA1NzI4OTkyLTZlMDE5YmRjLWNlMDktNGQ1OS1iMzAyLTY2MDQyMGIwNmFhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwMjMxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmYxN2YzMjUxMzA5MjFkM2ZhOWFmMDcxYmQ0MjI3ZmFkMTUwNGQ5NTkxMzUzMjBkYmVhY2RkYjdlMGU4OWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6O2kC8OHqhg_XJO3bnOiAiGeIfDpnTbCrE-mxxktTzc) ![Screenshot 2024-02-19 000316](https://private-user-images.githubusercontent.com/125168545/305729126-60b179cb-24da-4465-9ed6-dd6e6f6af803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjI5NzcsIm5iZiI6MTcxNDk2MjY3NywicGF0aCI6Ii8xMjUxNjg1NDUvMzA1NzI5MTI2LTYwYjE3OWNiLTI0ZGEtNDQ2NS05ZWQ2LWRkNmU2ZjZhZjgwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwMjMxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTY1MTU4ZDc1ODIyNjNkNzg2ZWRiYmQ5Yjc3NThiNWFhOGQwMTU2MDhmYzQ2NjE5OGYwNmQ4ZDIwNzI2ODNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VD2VXJIFVKhXHZ133pwy4kx9w2VNjAXrn1aA0p7dLl0)

谢谢！我现在能打开了。我没有找到之前为什么不能打开而现在能打开之具体原因。
自从用了openclash，我收集了很多的免费的节点订阅的地址，一百来个地址。在这地址逐渐增多的长时间的过程中，我发现我和openclash之间的交互操作变得非常艰难，一个点击下去，好几分钟没得op的反应。实时操作变成了和冥王星之间的通信，能憋出郁郁症。期间升级和降级op好几次，没有效果。
有次我在op的『配置管理』里把所有的配置文件都『移除』了，从新下载了正在使用的只有一个的订阅的节点配置，然后发现和op的互操作开始有效起来了，虽然还是有那么两三秒的慢。但我已经很治愈了。核心问题是，节点配置文件不能多，多于十个就有便秘之虞。
然后在某一天，我试图去打开我此前已经死心的yacd，哈哈哈，可以了。
我没有找到之前为什么不能打开而现在能打开之具体原因。

**Comment by Lumny-K** [comment]
@jacobin 
公用节点每隔一段时间就会被墙，特别事国庆期间，我有三十多个订阅都被污染了。控制面板容易抽风，我也是一直不段的升级，降级，最后切换为meta核心后才一切正常。

**Comment by jacobin** [comment]
> @jacobin 公用节点每隔一段时间就会被墙，特别事国庆期间，我有三十多个订阅都被污染了。控制面板容易抽风，我也是一直不段的升级，降级，最后切换为meta核心后才一切正常。

我也曾有花钱买googleVM自建机场的经历，爽了有那么大半年，然后在某一天开始就抽搐起来了，极其不稳定，看144p都不得爽过10分钟。拉闸换ip都不行。
换了其它的VM亦然。
然后我就开始搜索、收集、筛选免费节点及其订阅，企图用大面积的IP和横跳策略来抵御流量嗅探，一直用到现在，四年了。
开会期间被墙那是无法避免的，它们甚至会直接拔断海底光缆的接入，从物理上，简单粗暴的搞你。
