### ISSUE TITLE
新增代理集后，服务启动失败

### ISSUE THREAD

**Issue by LarkinZero** [vernesong/OpenClash#1058]
一个无代理集的配置，新增一个代理集后，保存应用，报错启动失败
```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0xd2dcc0, 0xb1c4e0)
	reflect/value.go:1894 +0x189
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeString(0xc000063638, 0xc0001fa060, 0xa, 0x0, 0x0, 0xb1c4e0, 0xc000117a30, 0x198, 0x2, 0xa)
	github.com/Dreamacro/clash/common/structure/structure.go:120 +0x14a
```

**Comment by LarkinZero** [comment]
环境信息
OpenClash 调试日志

生成时间: 2020-12-05 12:35:42
插件版本: v0.41.06-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#
主机型号: VMware, Inc. VMware Virtual Platform
固件版本: Openwrt Koolshare mod V2.36 r14941-67f6fa0a30
LuCI版本: git-20.074.84698-ead5e81
内核版本: 5.4.52
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: hybrid

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
iptables-mod-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
进程pid: 16680
运行权限: 16680: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_resource=i
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.11.23.g4474306
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v1.3.0-2-g994cbff
Dev内核文件: 存在
Dev内核运行权限: 正常

**Comment by vernesong** [comment]
配置文件写对了没

**Comment by LarkinZero** [comment]
> 配置文件写对了没

我检查了配置文件，发现proxy-providers被写入到了文件尾部，在`  - MATCH`后面，没有发现其他配置文件的异常
