### ISSUE TITLE
Clash内核崩溃BUG

### ISSUE THREAD

**Issue by SliverGod** [vernesong/OpenClash#1586]
以下情况必崩溃：
1. windows系统代理设置 ip:port
2. IDM程序设置代理下载
3. Pycharm爬虫设置proxy代理

仅有通过浏览器设置代理插件的形式是正常运行

希望可以得到解决办法，谢谢了，小白一枚，感谢大佬提供的插件，十分想解决，很多东西都需要用到~~

崩溃日志：

> github.com/Dreamacro/clash/listener/mixed/mixed.go:59 +0x88
  created by github.com/Dreamacro/clash/listener/mixed.New.func1
	  github.com/Dreamacro/clash/listener/mixed/mixed.go:79 +0x260
  github.com/Dreamacro/clash/listener/mixed.handleConn({0x55f818, 0x4000406008}, 0x400006c660, 0x400000ea30)
	  github.com/Dreamacro/clash/listener/http/proxy.go:32 +0x2c8
  github.com/Dreamacro/clash/listener/http.HandleConn({0x55d770, 0x40005767f8}, 0x400006c660, 0x400000ea30)
  goroutine 213 [running]:
  [signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x3c0c68]
  panic: runtime error: invalid memory address or nil pointer dereference
  2021-09-01 17:06:54 level=info msg="Start initial compatible provider ⚓️"
  2021-09-01 17:06:54 level=info msg="Start initial compatible provider 🚀"
  2021-09-01 17:06:54 level=info msg="Start initial compatible provider 🎬"
  2021-09-01 17:06:54 level=info msg="Start initial compatible provider ✈️"
  2021-09-01 17:06:54 level=info msg="Start initial compatible provider 🎬"
  2021-09-01 17:06:54 level=info msg="Start initial compatible provider 🍎"
  2021-09-01 17:06:54 level=info msg="Start initial compatible provider 🎬"
  2021-09-01 17:06:54 level=info msg="Start initial compatible provider 🎬"
  2021-09-01 17:06:54 level=info msg="Start initial compatible provider 🗿"
  2021-09-01 17:06:54 守护程序：检测到 Clash 内核崩溃，重启中...

**Comment by vernesong** [comment]
更新内核

**Comment by SliverGod** [comment]
好的
不过已经重置系统 重新来了，已经解决了，谢谢解答

**Comment by zhangguanzhang** [comment]
解决了就把issue关闭了

**Comment by SliverGod** [comment]
> 解决了就把issue关闭了

谢谢提醒
