### ISSUE TITLE
检测到 Clash 内核崩溃，重启中

### ISSUE THREAD

**Issue by a76yyyy** [vernesong/OpenClash#1634]
```
2021-09-13 01:07:06 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/common/picker/picker.go:64 +0x60
created by github.com/Dreamacro/clash/common/picker.(*Picker).Go
	github.com/Dreamacro/clash/common/picker/picker.go:67 +0x58
github.com/Dreamacro/clash/common/picker.(*Picker).Go.func1(0x40000e7c20, 0x400023f5c0)
	github.com/Dreamacro/clash/dns/resolver.go:159 +0x60
github.com/Dreamacro/clash/dns.(*Resolver).batchExchange.func1()
goroutine 38575 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x39e7e0]
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by thisdk** [comment]
同款问题,在0.43.05-bate版本下频繁出现,之前都不会这样

**Comment by zhangguanzhang** [comment]
```
2021-09-25 06:04:26 第六步：删除 OpenClash 残留文件...
2021-09-25 06:04:26 第五步: 重启 Dnsmasq 程序...
2021-09-25 06:04:26 第四步: 关闭 Clash 主程序...
2021-09-25 06:04:26 第三步: 关闭 OpenClash 守护程序...
2021-09-25 06:04:26 第二步: 删除 OpenClash 防火墙规则...
2021-09-25 06:04:26 第一步: 备份当前策略组状态...
2021-09-25 06:04:26 OpenClash 开始关闭...
2021-09-25 06:04:26 守护程序：已尝试自动重启三次 Clash 内核，为防止频繁重启造成严重后果，OpenClash 将停止运行...
2021-09-25 06:03:23 守护程序：检测到 Clash 内核崩溃，重启中...
2021-09-25 06:02:20 守护程序：检测到 Clash 内核崩溃，重启中...
2021-09-25 06:01:17 守护程序：检测到 Clash 内核崩溃，重启中...
2021-09-25 06:00:17 OpenClash 启动成功，请等待服务器上线！
2021-09-25 06:00:17 第十步: 添加计划任务,启动进程守护程序...
2021-09-25 06:00:17 第九步: 重启 Dnsmasq 程序...
2021-09-25 06:00:16 第八步: 设置防火墙规则...
2021-09-25 06:00:16 第七步: 设置控制面板...
2021-09-25 06:00:16 第六步: 等待主程序下载外部文件...
2021-09-25 06:00:13 第五步: 检查内核启动状态...
2021-09-25 06:00:10 未检测到特殊配置，调用 Dev 内核启动...
2021-09-25 06:00:10 第四步: 启动主程序...
2021-09-25 06:00:10 第三步: 修改配置文件...
2021-09-25 06:00:10 第二步: 组件运行前检查...
2021-09-25 06:00:10 第一步: 获取配置...
```

**Comment by zhangguanzhang** [comment]
你这有更详细的日志吗

**Comment by zhangguanzhang** [comment]
```
2021-09-25 06:00:13 Step 5: Check The Core Status...
time="2021-09-25T06:00:14+08:00" level=warning msg="MMDB invalid, remove and download"
2021-09-25 06:00:16 Step 6: Wait For The File Downloading...
2021-09-25 06:00:16 Step 7: Set Control Panel...
2021-09-25 06:00:16 Step 8: Set Firewall Rules...
2021-09-25 06:00:17 Step 9: Restart Dnsmasq...
2021-09-25 06:00:17 Step 10: Add Cron Rules, Start Daemons...
2021-09-25 06:00:17 OpenClash Start Successful!
time="2021-09-25T06:00:34+08:00" level=fatal msg="Initial configuration directory error: can't initial MMDB: can't download MMDB: Get \"https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb\": dial tcp: lookup cdn.jsdelivr.net on [::1]:53: read udp [::1]:45858->[::1]:53: i/o timeout"
2021-09-25 06:01:17 Watchdog: Clash Core Problem, Restart...
time="2021-09-25T06:01:17+08:00" level=info msg="Can't find MMDB, start download"
time="2021-09-25T06:01:37+08:00" level=fatal msg="Initial configuration directory error: can't initial MMDB: can't download MMDB: Get \"https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb\": dial tcp: lookup cdn.jsdelivr.net on [::1]:53: read udp [::1]:42178->[::1]:53: i/o timeout"
2021-09-25 06:02:20 Watchdog: Clash Core Problem, Restart...
time="2021-09-25T06:02:20+08:00" level=info msg="Can't find MMDB, start download"
time="2021-09-25T06:02:40+08:00" level=fatal msg="Initial configuration directory error: can't initial MMDB: can't download MMDB: Get \"https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb\": dial tcp: lookup cdn.jsdelivr.net on [::1]:53: read udp [::1]:50915->[::1]:53: i/o timeout"
2021-09-25 06:03:23 Watchdog: Clash Core Problem, Restart...
time="2021-09-25T06:03:23+08:00" level=info msg="Can't find MMDB, start download"
time="2021-09-25T06:03:43+08:00" level=fatal msg="Initial configuration directory error: can't initial MMDB: can't download MMDB: Get \"https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb\": dial tcp: lookup cdn.jsdelivr.net on [::1]:53: read udp [::1]:45645->[::1]:53: i/o timeout"
2021-09-25 06:04:26 Watchdog: Already Restart 3 Times With Clash Core Problem, Auto-Exit...

```

**Comment by thisdk** [comment]
> 你这有更详细的日志吗

后面没出现了,那天dev内核刚好升级到1.7.1,估计是那时候的dev内核有问题

**Comment by a76yyyy** [comment]
> > 你这有更详细的日志吗
> 
> 后面没出现了,那天dev内核刚好升级到1.7.1,估计是那时候的dev内核有问题

+1
