### ISSUE TITLE
求助， 无法启动OpenClash， 尝试还原默认配置失败

### ISSUE THREAD

**Issue by XinSSS** [vernesong/OpenClash#1761]
http://192.168.1.1/cgi-bin/luci/admin/services/openclash/restore 还原配置， 可是配置好像并没有还原

#===================== 最近运行日志 =====================#

panic: invalid freelist page: 0, page type is unknown<00>

goroutine 1 [running]:
go.etcd.io/bbolt.(*freelist).read(0x8f57a3, 0x7fa34db38000)
	go.etcd.io/bbolt@v1.3.6/freelist.go:266 +0x234
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
	go.etcd.io/bbolt@v1.3.6/db.go:323 +0xae
sync.(*Once).doSlow(0xc000381a88, 0x10)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	sync/once.go:59
go.etcd.io/bbolt.(*DB).loadFreelist(0xc0003818c0)
	go.etcd.io/bbolt@v1.3.6/db.go:316 +0x47
go.etcd.io/bbolt.Open({0xc00002a1f8, 0x17}, 0xe030, 0x0)
	go.etcd.io/bbolt@v1.3.6/db.go:293 +0x46b
github.com/Dreamacro/clash/component/profile/cachefile.migrateCache()
	github.com/Dreamacro/clash/component/profile/cachefile/cache.go:156 +0x252
sync.(*Once).doSlow(0xc0000265ac, 0xc0000ab460)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	sync/once.go:59
github.com/Dreamacro/clash/component/profile/cachefile.Cache(...)
	github.com/Dreamacro/clash/component/profile/cachefile/cache.go:178
github.com/Dreamacro/clash/component/fakeip.New({0xc0003650b0, 0xc00000e020, 0x9, 0xa0})
	github.com/Dreamacro/clash/component/fakeip/pool.go:159 +0x1bd
github.com/Dreamacro/clash/config.parseDNS(0xc00009e200, 0xc00000e008)
	github.com/Dreamacro/clash/config/config.go:602 +0x437
github.com/Dreamacro/clash/config.ParseRawConfig(0xc00009e200)
	github.com/Dreamacro/clash/config/config.go:230 +0x15d
github.com/Dreamacro/clash/config.Parse({0xc000180000, 0x1a, 0x7fa3747c75b8})
	github.com/Dreamacro/clash/config/config.go:158 +0x36
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
	github.com/Dreamacro/clash/hub/executor/executor.go:62
github.com/Dreamacro/clash/hub/executor.ParseWithPath({0x7ffd0fd1fb65, 0x0})
	github.com/Dreamacro/clash/hub/executor/executor.go:57 +0x3c
github.com/Dreamacro/clash/hub/executor.Parse(...)
	github.com/Dreamacro/clash/hub/executor/executor.go:47
github.com/Dreamacro/clash/hub.Parse({0x0, 0x0, 0x8f5f7e})
	github.com/Dreamacro/clash/hub/hub.go:31 +0x3d
main.main()
	github.com/Dreamacro/clash/main.go:99 +0x78b
2021-11-17 20:54:34 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again...
2021-11-17 20:54:35 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File
2021-11-17 20:54:38 OpenClash Stoping...
2021-11-17 20:54:38 Step 1: Backup The Current Groups State...
2021-11-17 20:54:38 Step 2: Delete OpenClash Firewall Rules...
2021-11-17 20:54:38 Step 3: Close The OpenClash Daemons...
2021-11-17 20:54:38 Step 4: Close The Clash Core Process...
2021-11-17 20:54:38 Step 5: Restart Dnsmasq...
2021-11-17 20:54:41 Step 6: Delete OpenClash Residue File...

#===================== 活动连接信息 =====================#

```

**Comment by XinSSS** [comment]
会不会是固件的问题呢。。我把配置和固件还原到了这个月6号的版本，OK了

**Comment by vernesong** [comment]
删除/etc/openclash/history里面的文件试试

**Comment by XinSSS** [comment]
@vernesong 都删了，还是无法启动

我注意到在我还原固件和配置， 然后又升级到今天刚编译的固件后还是能运行的， 那个时候Dev内核版本是1.71.5 ？ 升级到1.71.24后好像就不行了

#===================== 最近运行日志 =====================#

time="2021-11-17T13:24:16Z" level=info msg="Start initial compatible provider StreamingSE"
time="2021-11-17T13:24:16Z" level=info msg="Start initial compatible provider JP"
time="2021-11-17T13:24:16Z" level=info msg="Start initial compatible provider Apple"
time="2021-11-17T13:24:16Z" level=info msg="Start initial compatible provider US"
time="2021-11-17T13:24:16Z" level=info msg="Start initial compatible provider Proxies"
time="2021-11-17T13:24:16Z" level=info msg="Start initial compatible provider OneDrive"
panic: invalid freelist page: 0, page type is unknown<00>

goroutine 1 [running]:
go.etcd.io/bbolt.(*freelist).read(0x0, 0x7f26c16ef000)
	go.etcd.io/bbolt@v1.3.6/freelist.go:266 +0x234
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
	go.etcd.io/bbolt@v1.3.6/db.go:323 +0xae
sync.(*Once).doSlow(0xc00037fa88, 0x10)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	sync/once.go:59
go.etcd.io/bbolt.(*DB).loadFreelist(0xc00037f8c0)
	go.etcd.io/bbolt@v1.3.6/db.go:316 +0x47
go.etcd.io/bbolt.Open({0xc0003ee0d8, 0x17}, 0x0, 0xc000055aa0)
	go.etcd.io/bbolt@v1.3.6/db.go:293 +0x46b
github.com/Dreamacro/clash/component/profile/cachefile.migrateCache.func1()
	github.com/Dreamacro/clash/component/profile/cachefile/cache.go:120 +0xb8
github.com/Dreamacro/clash/component/profile/cachefile.migrateCache()
	github.com/Dreamacro/clash/component/profile/cachefile/cache.go:141 +0x34b
sync.(*Once).doSlow(0x203000, 0x203000)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	sync/once.go:59
github.com/Dreamacro/clash/component/profile/cachefile.Cache(...)
	github.com/Dreamacro/clash/component/profile/cachefile/cache.go:178
github.com/Dreamacro/clash/hub/executor.patchSelectGroup(0xcedcf0)
	github.com/Dreamacro/clash/hub/executor/executor.go:231 +0x49
github.com/Dreamacro/clash/hub/executor.updateProfile(0xc000180000)
	github.com/Dreamacro/clash/hub/executor/executor.go:226 +0x32
github.com/Dreamacro/clash/hub/executor.ApplyConfig(0xc0003057a0, 0xb0)
	github.com/Dreamacro/clash/hub/executor/executor.go:74 +0xf9
github.com/Dreamacro/clash/hub.Parse({0x0, 0x0, 0x8f5f7e})
	github.com/Dreamacro/clash/hub/hub.go:48 +0x18d
main.main()
	github.com/Dreamacro/clash/main.go:99 +0x78b
2021-11-17 21:24:20 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again...
2021-11-17 21:24:20 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File
2021-11-17 21:24:22 OpenClash Stoping...
2021-11-17 21:24:22 Step 1: Backup The Current Groups State...
2021-11-17 21:24:22 Step 2: Delete OpenClash Firewall Rules...
2021-11-17 21:24:23 Step 3: Close The OpenClash Daemons...
2021-11-17 21:24:23 Step 4: Close The Clash Core Process...
2021-11-17 21:24:23 Step 5: Restart Dnsmasq...
2021-11-17 21:24:26 Step 6: Delete OpenClash Residue File...

#===================== 活动连接信息 =====================#

我再还原下配置， 看看之前的内核是否OK

**Comment by vernesong** [comment]
跟固件没关系，1.71.24以后的数据库改了，所以你更新后尝试删除一下history文件

**Comment by XinSSS** [comment]
@vernesong /etc/openclash/history 目录里的文件都删除了， 1.71.24还是无法启动

OpenClash 调试日志

生成时间: 2021-11-18 20:04:10
插件版本: v0.43.09-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: Intel(R) Celeron(R) CPU 3865U @ 1.80GHz : 2 Core 2 Thread
固件版本: OpenWrt SNAPSHOT r3899-495fe886a
LuCI版本: git-21.320.49600-21168d4-1
内核版本: 5.4.158
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
ruby-dbm: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#

运行状态: 未运行
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2021.09.07
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.7.1-24-gebbc960
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/MYIPLC.yaml
启动配置文件: /etc/openclash/MYIPLC.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 自定义规则 一 =====================#
- SRC-PORT,6771,DIRECT
- SRC-PORT,22223,DIRECT
- SRC-PORT,27916,DIRECT
- SRC-PORT,51413,DIRECT
- SRC-PORT,9405,Proxies
- SRC-PORT,9505,Proxies
- SRC-IP-CIDR,192.168.1.111/32,DIRECT
- SRC-IP-CIDR,192.168.1.116/32,DIRECT
- SRC-IP-CIDR,192.168.1.113/32,Streaming
- SRC-IP-CIDR,192.168.1.114/32,Streaming
#===================== 自定义规则 二 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

#===================== 配置文件 =====================#

port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  nameserver:
  - 223.5.5.5
  - 119.29.29.29
  fallback:
  - 8.8.8.8
  - tls://8.8.8.8:853
  - tcp://1.1.1.1:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - swscan.apple.com
  - mesu.apple.com
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - "+.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - "+.y.qq.com"
  - "+.music.tc.qq.com"
  - aqqmusic.tc.qq.com
  - "+.stream.qqmusic.qq.com"
  - "*.xiami.com"
  - "+.music.migu.cn"
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - "+.xboxlive.com"
  - localhost.ptlogin2.qq.com
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.battlenet.com.cn"
tun:
  enable: false
  stack: system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
external-controller: 127.0.0.1:9090
proxy-groups:
#===================== 规则省略。。。。 =====================#
- GEOIP,CN,China
- MATCH,Final

#===================== 防火墙设置 =====================#

#IPv4 NAT chain

# Generated by iptables-save v1.8.7 on Thu Nov 18 20:04:11 2021
*nat
:PREROUTING ACCEPT [1424:380719]
:INPUT ACCEPT [1042:296538]
:OUTPUT ACCEPT [188:12843]
:POSTROUTING ACCEPT [230:29401]
:MINIUPNPD - [0:0]
:MINIUPNPD-POSTROUTING - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i pppoe-wan -m comment --comment "!fw3" -j zone_wan_prerouting
-A PREROUTING -i eth0 -m comment --comment "!fw3" -j zone_wan_prerouting
-A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A POSTROUTING -o pppoe-wan -m comment --comment "!fw3" -j zone_wan_postrouting
-A POSTROUTING -o eth0 -m comment --comment "!fw3" -j zone_wan_postrouting
-A MINIUPNPD -p tcp -m tcp --dport 32391 -j DNAT --to-destination 192.168.1.116:9010
-A MINIUPNPD -p tcp -m tcp --dport 36040 -j DNAT --to-destination 192.168.1.116:9020
-A MINIUPNPD -p udp -m udp --dport 31480 -j DNAT --to-destination 192.168.1.116:9030
-A MINIUPNPD -p udp -m udp --dport 34056 -j DNAT --to-destination 192.168.1.116:9031
-A MINIUPNPD -p udp -m udp --dport 39835 -j DNAT --to-destination 192.168.1.116:9032
-A MINIUPNPD -p udp -m udp --dport 32015 -j DNAT --to-destination 192.168.1.116:9033
-A MINIUPNPD -p udp -m udp --dport 3074 -j DNAT --to-destination 192.168.1.104:3074
-A MINIUPNPD -p udp -m udp --dport 25599 -j DNAT --to-destination 192.168.1.104:25599
-A MINIUPNPD -p tcp -m tcp --dport 57895 -j DNAT --to-destination 192.168.1.111:4610
-A MINIUPNPD-POSTROUTING -s 192.168.1.116/32 -p tcp -m tcp --sport 9010 -j MASQUERADE --to-ports 32391
-A MINIUPNPD-POSTROUTING -s 192.168.1.116/32 -p tcp -m tcp --sport 9020 -j MASQUERADE --to-ports 36040
-A MINIUPNPD-POSTROUTING -s 192.168.1.116/32 -p udp -m udp --sport 9030 -j MASQUERADE --to-ports 31480
-A MINIUPNPD-POSTROUTING -s 192.168.1.116/32 -p udp -m udp --sport 9031 -j MASQUERADE --to-ports 34056
-A MINIUPNPD-POSTROUTING -s 192.168.1.116/32 -p udp -m udp --sport 9032 -j MASQUERADE --to-ports 39835
-A MINIUPNPD-POSTROUTING -s 192.168.1.116/32 -p udp -m udp --sport 9033 -j MASQUERADE --to-ports 32015
-A MINIUPNPD-POSTROUTING -s 192.168.1.111/32 -p tcp -m tcp --sport 4610 -j MASQUERADE --to-ports 57895
-A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
-A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
-A zone_wan_postrouting -j MINIUPNPD-POSTROUTING
-A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
-A zone_wan_postrouting -m comment --comment "!fw3" -j FULLCONENAT
-A zone_wan_prerouting -j MINIUPNPD
-A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
-A zone_wan_prerouting -m comment --comment "!fw3" -j FULLCONENAT
COMMIT
# Completed on Thu Nov 18 20:04:11 2021

#IPv4 Mangle chain

# Generated by iptables-save v1.8.7 on Thu Nov 18 20:04:11 2021
*mangle
:PREROUTING ACCEPT [11133:4907075]
:INPUT ACCEPT [8575:4630338]
:FORWARD ACCEPT [2467:214479]
:OUTPUT ACCEPT [5898:2996077]
:POSTROUTING ACCEPT [8299:3207208]
-A FORWARD -o pppoe-wan -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A FORWARD -i pppoe-wan -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A FORWARD -o eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A FORWARD -i eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
COMMIT
# Completed on Thu Nov 18 20:04:11 2021

#IPv6 NAT chain


#IPv6 Mangle chain


#===================== IPSET状态 =====================#

Name: china

#===================== 路由表状态 =====================#

#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         115.199.152.1   0.0.0.0         UG    0      0        0 pppoe-wan
115.199.152.1   0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 115.199.152.1 dev pppoe-wan proto static 
115.199.152.1 dev pppoe-wan proto kernel scope link src 115.199.158.144 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
#ip rule show
0:	from all lookup local
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#


#===================== 测试本机DNS查询 =====================#

Server:		127.0.0.1
Address:	127.0.0.1:53

Non-authoritative answer:
www.baidu.com	canonical name = www.a.shifen.com

Non-authoritative answer:
www.baidu.com	canonical name = www.a.shifen.com
Name:	www.a.shifen.com
Address: 180.101.49.11
Name:	www.a.shifen.com
Address: 180.101.49.12


#===================== resolv.conf.d =====================#

# Interface wan
nameserver 223.5.5.5
nameserver 119.29.29.29

#===================== 测试本机网络连接 =====================#

HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Thu, 18 Nov 2021 12:04:11 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 80
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "ade92b0bfd2951f6f2167a0db2526a0ba2121e8ae1a073846f6c9c10d3849c05"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: AF68:6D70:3A809F:462363:619637F8
Accept-Ranges: bytes
Date: Thu, 18 Nov 2021 12:04:18 GMT
Via: 1.1 varnish
X-Served-By: cache-nrt18349-NRT
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1637237059.807424,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 97ad7b4d27677d2d546f2654c5ce168ce718339a
Expires: Thu, 18 Nov 2021 12:09:18 GMT
Source-Age: 196


#===================== 最近运行日志 =====================#

time="2021-11-18T12:03:51Z" level=info msg="Start initial compatible provider TW"
time="2021-11-18T12:03:51Z" level=info msg="Start initial compatible provider HK"
time="2021-11-18T12:03:51Z" level=info msg="Start initial compatible provider Final"
time="2021-11-18T12:03:51Z" level=info msg="Start initial compatible provider PayPal"
time="2021-11-18T12:03:51Z" level=info msg="Start initial compatible provider StreamingSE"
time="2021-11-18T12:03:51Z" level=info msg="Start initial compatible provider US"
panic: invalid freelist page: 0, page type is unknown<00>

goroutine 1 [running]:
go.etcd.io/bbolt.(*freelist).read(0x0, 0x7f5a11e8f000)
	go.etcd.io/bbolt@v1.3.6/freelist.go:266 +0x234
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
	go.etcd.io/bbolt@v1.3.6/db.go:323 +0xae
sync.(*Once).doSlow(0xc0003bb848, 0x10)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	sync/once.go:59
go.etcd.io/bbolt.(*DB).loadFreelist(0xc0003bb680)
	go.etcd.io/bbolt@v1.3.6/db.go:316 +0x47
go.etcd.io/bbolt.Open({0xc0004280d8, 0x17}, 0x0, 0xc000113aa0)
	go.etcd.io/bbolt@v1.3.6/db.go:293 +0x46b
github.com/Dreamacro/clash/component/profile/cachefile.migrateCache.func1()
	github.com/Dreamacro/clash/component/profile/cachefile/cache.go:120 +0xb8
github.com/Dreamacro/clash/component/profile/cachefile.migrateCache()
	github.com/Dreamacro/clash/component/profile/cachefile/cache.go:141 +0x34b
sync.(*Once).doSlow(0x203000, 0x203000)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	sync/once.go:59
github.com/Dreamacro/clash/component/profile/cachefile.Cache(...)
	github.com/Dreamacro/clash/component/profile/cachefile/cache.go:178
github.com/Dreamacro/clash/hub/executor.patchSelectGroup(0xcedcf0)
	github.com/Dreamacro/clash/hub/executor/executor.go:231 +0x49
github.com/Dreamacro/clash/hub/executor.updateProfile(0xc0001a6000)
	github.com/Dreamacro/clash/hub/executor/executor.go:226 +0x32
github.com/Dreamacro/clash/hub/executor.ApplyConfig(0xc00033f730, 0x20)
	github.com/Dreamacro/clash/hub/executor/executor.go:74 +0xf9
github.com/Dreamacro/clash/hub.Parse({0x0, 0x0, 0x8f5f7e})
	github.com/Dreamacro/clash/hub/hub.go:48 +0x18d
main.main()
	github.com/Dreamacro/clash/main.go:99 +0x78b
2021-11-18 20:03:55 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again...
2021-11-18 20:03:56 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File
2021-11-18 20:03:58 OpenClash Stoping...
2021-11-18 20:03:58 Step 1: Backup The Current Groups State...
2021-11-18 20:03:58 Step 2: Delete OpenClash Firewall Rules...
2021-11-18 20:03:58 Step 3: Close The OpenClash Daemons...
2021-11-18 20:03:58 Step 4: Close The Clash Core Process...
2021-11-18 20:03:58 Step 5: Restart Dnsmasq...
2021-11-18 20:04:01 Step 6: Delete OpenClash Residue File...

#===================== 活动连接信息 =====================#


```

**Comment by vernesong** [comment]
rm -rf /etc/openclash/.cache /etc/openclash/cache.db

**Comment by XinSSS** [comment]
@vernesong 感谢 ！ 问题解决了
