### ISSUE TITLE
Meta内核，规则同时包含AND和SRC-IP-CIDR时内核崩溃

### ISSUE THREAD

**Issue by htfcuddles** [vernesong/OpenClash#2272]
- 版本v0.45.02-beta，Meta内核alpha-g21446ba

- 规则如下：

`- AND,((SRC-IP-CIDR,192.168.1.1/32),(NETWORK,UDP),(DST-PORT,10001-65535)),DIRECT`

内核启动崩溃，报错日志如下：
```
	github.com/Dreamacro/clash/main.go:105 +0x7cb
main.main()
	github.com/Dreamacro/clash/hub/hub.go:31 +0x3d
github.com/Dreamacro/clash/hub.Parse({0x0, 0x0, 0xdb3837?})
	github.com/Dreamacro/clash/hub/executor/executor.go:54
github.com/Dreamacro/clash/hub/executor.Parse(...)
	github.com/Dreamacro/clash/hub/executor/executor.go:64 +0x3c
github.com/Dreamacro/clash/hub/executor.ParseWithPath({0x7ffe22a66acc?, 0xc0000d3e48?})
	github.com/Dreamacro/clash/hub/executor/executor.go:69
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
	github.com/Dreamacro/clash/config/config.go:230 +0x36
github.com/Dreamacro/clash/config.Parse({0xc0002c6000?, 0x1a?, 0x7f82a48295b8?})
	github.com/Dreamacro/clash/config/config.go:334 +0x26d
github.com/Dreamacro/clash/config.ParseRawConfig(0xc0000ee900)
	github.com/Dreamacro/clash/config/config.go:573 +0x78d
github.com/Dreamacro/clash/config.parseRules(0xc0000ee900, 0xc57fe0?)
	github.com/Dreamacro/clash/rule/parser.go:49 +0x368
github.com/Dreamacro/clash/rule.ParseRule({0xc0000cb040?, 0xc000319ef0?}, {0xc0000cb810, 0x43}, {0xc0000cb089, 0x6}, {0x0?, 0x0, 0x0})
	github.com/Dreamacro/clash/rule/logic/and.go:24 +0xc9
github.com/Dreamacro/clash/rule/logic.NewAND({0xc0000cb810, 0x43}, {0xc0000cb089, 0x6})
	github.com/Dreamacro/clash/rule/logic/common.go:35 +0x24e
github.com/Dreamacro/clash/rule/logic.parseRuleByPayload({0xc0000cb810, 0x43}, 0x1)
	github.com/Dreamacro/clash/rule/logic/common.go:71 +0x189
github.com/Dreamacro/clash/rule/logic.payloadToRule({0xc0000cb812?, 0xc000310e28?})
	github.com/Dreamacro/clash/rule/logic/common.go:96 +0x3e7
github.com/Dreamacro/clash/rule/logic.parseRule({0xc0000cb812?, 0x10?}, {0xc0000cb81e, 0x10}, {0xc00037f030?, 0x0, 0x0})
	github.com/Dreamacro/clash/rule/common/ipcidr.go:71 +0xff
github.com/Dreamacro/clash/rule/common.NewIPCIDR({0xc0000cb81e?, 0x203000?}, {0x0, 0x0}, {0xc0000d3668, 0x3, 0x0?})
goroutine 1 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b43ff]
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by htfcuddles** [comment]
已提交https://github.com/MetaCubeX/Clash.Meta/issues/41

**Comment by MetaCubeX** [comment]
已记录

**Comment by MetaCubeX** [comment]
> 已提交[MetaCubeX/Clash.Meta#41](https://github.com/MetaCubeX/Clash.Meta/issues/41)

已修复
