### ISSUE TITLE
[Bug] 错误：Ruby 依赖异常，无法校验配置文件，请确认 Ruby 依赖工作正常后重试！

### ISSUE THREAD

**Issue by zhilun2021** [vernesong/OpenClash#2512]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.33-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv8

### To Reproduce

2022-06-27 00:43:41 错误：Ruby 依赖异常，无法校验配置文件，请确认 Ruby 依赖工作正常后重试！
2022-06-27 00:43:41 第三步: 修改配置文件...
2022-06-27 00:43:41 第二步: 组件运行前检查...
2022-06-27 00:43:41 第一步: 获取配置...
2022-06-27 00:43:41 OpenClash 开始启动...

### Describe the Bug

依赖全部安装好后，安装Luci-app-clash成功，导入配置提示语法错误，启动openclash提示 错误：Ruby 依赖异常，无法校验配置文件，请确认 Ruby 依赖工作正常后重试！

### OpenClash Log

2022-06-27 00:43:45 OpenClash 开始关闭...
2022-06-27 00:43:41 错误：Ruby 依赖异常，无法校验配置文件，请确认 Ruby 依赖工作正常后重试！
2022-06-27 00:43:41 第三步: 修改配置文件...
2022-06-27 00:43:41 第二步: 组件运行前检查...
2022-06-27 00:43:41 第一步: 获取配置...
2022-06-27 00:43:41 OpenClash 开始启动...
2022-06-27 00:43:41 第六步：删除 OpenClash 残留文件...
2022-06-27 00:43:38 第五步: 重启 Dnsmasq 程序...
2022-06-27 00:43:38 第四步: 关闭 Clash 主程序...
2022-06-27 00:43:38 第三步: 关闭 OpenClash 守护程序...
2022-06-27 00:43:37 第二步: 删除 OpenClash 防火墙规则...
2022-06-27 00:43:37 第一步: 备份当前策略组状态...
2022-06-27 00:43:37 OpenClash 开始关闭...
2022-06-27 00:41:32 第六步：删除 OpenClash 残留文件...
2022-06-27 00:41:29 第五步: 重启 Dnsmasq 程序...
2022-06-27 00:41:29 第四步: 关闭 Clash 主程序...
2022-06-27 00:41:29 第三步: 关闭 OpenClash 守护程序...
2022-06-27 00:41:28 第二步: 删除 OpenClash 防火墙规则...
2022-06-27 00:41:28 第一步: 备份当前策略组状态...
2022-06-27 00:41:28 OpenClash 开始关闭...
2022-06-27 00:41:24 错误：Ruby 依赖异常，无法校验配置文件，请确认 Ruby 依赖工作正常后重试！
2022-06-27 00:41:24 第三步: 修改配置文件...
2022-06-27 00:41:24 第二步: 组件运行前检查...
2022-06-27 00:41:24 第一步: 获取配置...
2022-06-27 00:41:24 OpenClash 开始启动...
2022-06-27 00:41:24 第六步：删除 OpenClash 残留文件...
2022-06-27 00:41:20 第五步: 重启 Dnsmasq 程序...
2022-06-27 00:41:20 第四步: 关闭 Clash 主程序...
2022-06-27 00:41:20 第三步: 关闭 OpenClash 守护程序...
2022-06-27 00:41:20 第二步: 删除 OpenClash 防火墙规则...
2022-06-27 00:41:20 第一步: 备份当前策略组状态...
2022-06-27 00:41:20 OpenClash 开始关闭...

### Expected Behavior

希望尽快修复这个问题。已经集成在固件的就正常。没集成openclash的固件。手动安装的就会出现这个错误。

### Screenshots

![QQ截图20220627005024](https://user-images.githubusercontent.com/86742791/175825110-5adef8f3-dcf9-459c-9242-bcd45a96b511.jpg)
![QQ截图20220627005037](https://user-images.githubusercontent.com/86742791/175825121-3cdd4a43-f977-4382-9d89-35e9afdca284.jpg)

**Comment by vernesong** [comment]
依赖问题没好办法，不是我们解决的

**Comment by jayling1111** [comment]
换个固件把

**Comment by crh251** [comment]
是依赖版本问题吗？回退到哪个openwrt版本可以正常用呢？

**Comment by wudj1967** [comment]
ruby版本可能不对，最好能降到3.0.4

**Comment by RuningBun** [comment]
降版本问题解决了么？

**Comment by wudj1967** [comment]
降版本就正常了

**Comment by lovelywanz** [comment]
今晚折腾了三个小时了，无论怎样尝试，都摆脱不了这个依赖异常错误。把所有ruby相关文件退回到3.0.4试过了，没用。把openclash和内核降级，也没用。

**Comment by joy08956** [comment]
> 依赖问题没好办法，不是我们解决的
root@QWRT:~# ruby -ryaml -E UTF-8 -e "YAML.load_file('/usr/share/openclash/res/default.yaml')"
/usr/lib/ruby/3.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/usr/lib/ruby/3.0/yaml.rb:4:in `require': cannot load such file -- psych (LoadError)
	from /usr/lib/ruby/3.0/yaml.rb:4:in `<top (required)>'
	from -e:in `require'

**Comment by markixy** [comment]
我是 openwrt18.06.9，给ruby-yaml降版本就好了。

原来长这样，所以盲猜ruby-yaml版本太高。
root@OpenWrt:~# opkg list-installed |grep ruby
libruby - 2.5.8-1
ruby - 2.5.8-1
...
ruby-yaml - 3.3.4-r1

解决方式：给ruby-yaml降版本
wget http://mirrors.aliyun.com/openwrt/releases/18.06.9/packages/x86_64/packages/ruby-yaml_2.5.8-1_x86_64.ipk
opkg install ruby-yaml_2.5.8-1_x86_64.ipk  --force-downgrade

**Comment by abining** [comment]
> ruby-strscan

```
root@OpenWrt:~# opkg install ruby-strscan
Unknown package 'ruby-strscan'.
Collected errors:
 * opkg_install_cmd: Cannot install package ruby-strscan.
```

**Comment by YesSanSan** [comment]
我也遇到了，写个自己的解决办法把
因为刚升级openclash，release的安装说明如下：

> #iptables
opkg update
opkg install bash iptables dnsmasq-full curl ca-bundle ipset ip-full iptables-mod-tproxy iptables-mod-extra ruby ruby-yaml kmod-tun kmod-inet-diag unzip luci-compat luci luci-base
opkg install /tmp/openclash.ipk

这个命令会导致ruby被升级到最新版本，而ruby-*这一堆还是旧版本的（libruby和ruby-yaml是我查找解决办法时手动升级的）
```
root@LEDE:/tmp# opkg list-installed | grep ruby
libruby3.3 - 3.3.5-r1
ruby - 3.3.5-r1
ruby-bigdecimal - 3.1.3-1
ruby-date - 3.1.3-1
ruby-digest - 3.1.3-1
ruby-enc - 3.1.3-1
ruby-forwardable - 3.1.3-1
ruby-pstore - 3.1.3-1
ruby-psych - 3.1.3-1
ruby-stringio - 3.1.3-1
ruby-strscan - 3.1.3-1
ruby-yaml - 3.3.5-r1
```
所以我更新了ruby-*这一堆：
```
root@LEDE:/tmp# opkg list-installed | grep ruby
libruby3.3 - 3.3.5-r1
ruby - 3.3.5-r1
ruby-bigdecimal - 3.3.5-r1
ruby-date - 3.3.5-r1
ruby-digest - 3.3.5-r1
ruby-enc - 3.3.5-r1
ruby-forwardable - 3.3.5-r1
ruby-pstore - 3.3.5-r1
ruby-psych - 3.3.5-r1
ruby-stringio - 3.3.5-r1
ruby-strscan - 3.3.5-r1
ruby-yaml - 3.3.5-r1
```
然后openclash恢复正常

因为旧版本的openclash都能正常运行，没道理新版本的openclash会依赖更老的ruby，所以我没有考虑降级，而是全部升级到最新版本，最后成功了

**Comment by sky2ree** [comment]
如何更新了ruby-*这一堆

**Comment by creazycar** [comment]
> 如何更新了ruby-*这一堆

软件包里搜索，升级

**Comment by gitzwt** [comment]
> 如何更新了ruby-*这一堆

opkg list-installed | grep ruby

然后逐个 opkg install ruby-*这一堆

**Comment by Darkylin** [comment]
```
opkg upgrade $(opkg list-installed | grep ruby | awk '{print $1}')
```

**Comment by disklight** [comment]
检查一下是否在误用了错误的软件源版本 https://mirrors.aliyun.com/openwrt/releases/v21.02-SNAPSHOT/
卸载ruby   `opkg remove ruby --force-removal-of-dependent-packages --force-remove`
重新安装clash让它自己安装依赖
