### ISSUE TITLE
[Bug] 启动后短时间内崩溃

### ISSUE THREAD

**Issue by ObcbO** [vernesong/OpenClash#3549]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

未知

### Describe the Bug

启动后仅代理不到10个流量就崩溃

### OpenClash Log

```
2023-10-06 09:20:42 第六步：删除 OpenClash 残留文件...
2023-10-06 09:20:35 第五步: 重启 Dnsmasq 程序...
2023-10-06 09:20:35 第四步: 关闭 Clash 主程序...
2023-10-06 09:20:35 第三步: 关闭 OpenClash 守护程序...
2023-10-06 09:20:32 第二步: 删除 OpenClash 防火墙规则...
2023-10-06 09:20:32 第一步: 备份当前策略组状态...
2023-10-06 09:20:32 OpenClash 开始关闭...
2023-10-06 09:20:32 守护程序：已尝试自动重启三次 Clash 内核，为防止频繁重启造成严重后果，OpenClash 将停止运行...
	reflect/value.go:2605
	reflect/value.go:2610 +0x12c
2023-10-06 09:19:28 守护程序：检测到 Clash 内核崩溃，重启中...
	reflect/value.go:2605
	reflect/value.go:2610 +0x12c
2023-10-06 09:18:25 守护程序：检测到 Clash 内核崩溃，重启中...
	reflect/value.go:2605
	reflect/value.go:2610 +0x12c
2023-10-06 09:17:22 守护程序：检测到 Clash 内核崩溃，重启中...
2023-10-06 09:16:21 OpenClash 启动成功，请等待服务器上线！
2023-10-06 09:16:21 第九步: 添加计划任务,启动进程守护程序...
2023-10-06 09:16:17 第八步: 重启 Dnsmasq 程序...
2023-10-06 09:16:17 提示：开始添加自定义防火墙规则...
2023-10-06 09:16:17 提示：正在根据防火墙端口转发和防火墙通信规则添加端口绕过规则...
2023-10-06 09:16:16 提示：正在等待 TUN 接口启动...
	reflect/value.go:2605
	reflect/value.go:2610 +0x12c
2023-10-06 09:16:02 提示：检测到 Firewall4，使用 NFTABLE 规则...
2023-10-06 09:16:02 提示：IPv6 代理模式为 TUN...
2023-10-06 09:16:02 提示：DNS 劫持模式为 Dnsmasq 转发...
2023-10-06 09:16:02 第七步: 设置防火墙规则...
2023-10-06 09:16:02 第六步: 等待主程序下载外部文件...
2023-10-06 09:15:59 第五步: 检查内核启动状态...
2023-10-06 09:15:58 配置文件【/etc/openclash/config.yaml】测试成功...
2023-10-06 09:15:49 启动前调用内核测试配置文件...
2023-10-06 09:15:49 提示：检测到配置了 Meta 内核专属功能，调用 Meta 内核启动...
2023-10-06 09:15:49 第四步: 启动主程序...
2023-10-06 09:15:49 提示：开始运行自定义覆写脚本...
2023-10-06 09:15:47 提示：您为 SOCKS5/HTTP(S) 代理设置的账户密码为【Clash:xxxxxx】
2023-10-06 09:15:46 第三步: 修改配置文件...
2023-10-06 09:15:46 提示：由于文件【 /etc/config/openclash 】被修改，暂停快速启动...
2023-10-06 09:15:46 第二步: 组件运行前检查...
2023-10-06 09:15:45 第一步: 获取配置...
2023-10-06 09:15:45 OpenClash 开始启动...
```
```
	github.com/Dreamacro/clash/hub/executor/executor.go:308 +0x78
created by github.com/Dreamacro/clash/hub/executor.loadProxyProvider
	github.com/Dreamacro/clash/hub/executor/executor.go:310 +0x74
github.com/Dreamacro/clash/hub/executor.loadProxyProvider.func1()
	github.com/Dreamacro/clash/hub/executor/executor.go:268 +0xd0
github.com/Dreamacro/clash/hub/executor.loadProvider({0x7f76816c50, 0x40000ac7b0})
	github.com/Dreamacro/clash/adapter/provider/provider.go:81 +0x30
github.com/Dreamacro/clash/adapter/provider.(*proxySetProvider).Initial(0x40003dd140)
	github.com/Dreamacro/clash/component/resource/fetcher.go:75 +0x258
github.com/Dreamacro/clash/component/resource.(*Fetcher[...]).Initial(0x113f440)
	github.com/Dreamacro/clash/adapter/provider/provider.go:361 +0x590
github.com/Dreamacro/clash/adapter/provider.proxiesParseAndFilter.func1({0x400356ea00, 0x1e90, 0x2500})
	github.com/Dreamacro/clash/adapter/parser.go:62 +0x650
github.com/Dreamacro/clash/adapter.ParseProxy(0xd24780?)
	github.com/Dreamacro/clash/common/structure/structure.go:80 +0x4a8
github.com/Dreamacro/clash/common/structure.(*Decoder).Decode(0x40010b8e10, 0x40036e2ab0?, {0xc702a0?, 0x40036c12c0})
	github.com/Dreamacro/clash/common/structure/structure.go:115 +0x264
github.com/Dreamacro/clash/common/structure.(*Decoder).decode(0xef6a80?, {0xc55b0b?, 0xc55b0b?}, {0xd241e0?, 0x40036e2b10?}, {0xd993c0?, 0x40036c1400?, 0x61684?})
	github.com/Dreamacro/clash/common/structure/structure.go:405 +0x268
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeStruct(0x40010b8918?, {0xc55b0b, 0x7}, {0xd241e0?, 0x40036e2b10?}, {0xd993c0?, 0x40036c1400?, 0xc55b04?})
	github.com/Dreamacro/clash/common/structure/structure.go:539 +0x788
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeStructFromMap(0x40010b8e10, {0xc55b0b, 0x7}, {0xd241e0?, 0x40036e2b10?, 0x9f71c?}, {0xd993c0?, 0x40036c1400?, 0x2200ef6a80?})
	github.com/Dreamacro/clash/common/structure/structure.go:105 +0x274
github.com/Dreamacro/clash/common/structure.(*Decoder).decode(0xcfb9e0?, {0x40036bbdf0?, 0x40010b82d8?}, {0x0?, 0x0?}, {0xcb6400?, 0x40036c1418?, 0x0?})
	github.com/Dreamacro/clash/common/structure/structure.go:244 +0x324
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeString(0x40010b8098?, {0x40036bbdf0?, 0xc?}, {0x0?, 0x0?}, {0xcb6400?, 0x40036c1418?, 0x68e1e4?})
reflect.Value.Type(...)
reflect.Value.typeSlow({0x0?, 0x0?, 0x40010b7fd8?})
goroutine 118 [running]:
panic: reflect: call of reflect.Value.Type on zero Value
2023-10-06 09:19:39 level=info msg="[TCP] clash.meta --> neko-warp.nloli.xyz:443 match Match using 🐟 漏网之鱼[🇭🇰HK-45102-Alibaba]"
```

### OpenClash Config

```shell
打开了IPV6 使用meta内核 fake-ip模式

all: &all
  proxies:
  - WARP
  use:
  - xxx

pr: &pr {type: select, proxies: [🚀 国外流量,🎯 国内流量,🌐 全球直连,🚫 全球屏蔽]}
p: &p {type: http, interval: 3600, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
pg: &pg {<<: *all, tolerance: 2, type: url-test}
pgb: &pgb {<<: *all, interval: 300, type: load-balance}

proxy-providers:
    xxxx

mode: rule
ipv6: true
log-level: info
allow-lan: true
mixed-port: 7890
unified-delay: false
tcp-concurrent: true

geodata-mode: true
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"

find-process-mode: strict
global-client-fingerprint: random

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 223.5.5.5
    - 1.1.1.1
    - 114.114.114.114
  nameserver:
    - tls://dns.alidns.com
    - tls://dot.pub
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
  fallback:
    - tls://dns.umbrella.com
    - tls://one.one.one.one
    - tls://dns.google
    - tls://dns.alidns.com
  proxy-server-nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.alidns.com/dns-query

proxy-groups:
  - {name: 🚀 国外流量, type: select, proxies: [♻️ 自动选择, 🔰 手动选择, 🌐 全球直连, 🚫 全球屏蔽, ⚖️ 负载均衡-散列, ⚖️ 负载均衡-轮询]}
  - {name: 🎯 国内流量, type: select, proxies: [🌐 全球直连, ♻️ 自动选择, 🔰 手动选择, 🚫 全球屏蔽, ⚖️ 负载均衡-散列, ⚖️ 负载均衡-轮询]}
  - {name: ♻️ 自动选择, <<: *pg, type: url-test}
  - {name: 🔰 手动选择, <<: *all, type: select}
  - {name: ⚖️ 负载均衡-散列, <<: *pgb, strategy: consistent-hashing}
  - {name: ⚖️ 负载均衡-轮询, <<: *pgb, strategy: round-robin}
  - {name: 🛑 广告拦截, type: select, proxies: [🚫 全球屏蔽, ♻️ 自动选择, 🔰 手动选择, 🌐 全球直连]}
  - {name: 🐟 漏网之鱼, <<: *pr}
  - {name: 🌐 全球直连, type: select, proxies: [DIRECT]}
  - {name: 🚫 全球屏蔽, type: select, proxies: [REJECT]}

rules:
  - DOMAIN-SUFFIX,api.installer.xiaomi.com,🚫 全球屏蔽
  - DOMAIN,flash.sec.miui.com,🚫 全球屏蔽
  - DOMAIN,a0.app.xiaomi.com,🚫 全球屏蔽
  - GEOSITE,category-ads-all,🛑 广告拦截
  - GEOSITE,microsoft@cn,🎯 国内流量
  - GEOSITE,github,🚀 国外流量
  - GEOSITE,twitter,🚀 国外流量
  - GEOSITE,youtube,🚀 国外流量
  - GEOSITE,google,🚀 国外流量
  - GEOSITE,telegram,🚀 国外流量
  - GEOSITE,netflix,🚀 国外流量
  - GEOSITE,spotify,🚀 国外流量
  - GEOIP,google,🚀 国外流量
  - GEOIP,netflix,🚀 国外流量
  - GEOIP,telegram,🚀 国外流量
  - GEOIP,twitter,🚀 国外流量
  - GEOSITE,geolocation-!cn,🚀 国外流量
  - GEOSITE,CN,🎯 国内流量
  - GEOIP,CN,🎯 国内流量
  - GEOIP,LAN,🌐 全球直连
  - MATCH,🐟 漏网之鱼
```
```


### Expected Behavior

无

### Screenshots

_No response_

**Comment by cosysun** [comment]
@ObcbO 请问这个问题最后是怎么解决的
