### ISSUE TITLE
[Bug] Meta核心无法工作

### ISSUE THREAD

**Issue by zlwu** [vernesong/OpenClash#3608]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.152-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

OpenClash升级到152-beta，meta核心升级到alpha-g8c3557e（均在openclash面板上升级）

### Describe the Bug

meta核心启动就崩溃了

### OpenClash Log

```txt
github.com/Dreamacro/clash/listener/redir/tcp.go:58 +0x136
created by github.com/Dreamacro/clash/listener/redir.New.func1 in goroutine 12
	github.com/Dreamacro/clash/listener/redir/tcp.go:72 +0xe4
github.com/Dreamacro/clash/listener/redir.handleRedir({0x1667590, 0xc00029a008}, {0x165a1e0, 0x2612460}, {0xc00040dc40, 0x2, 0x2})
	github.com/Dreamacro/clash/tunnel/tunnel.go:58 +0x2c
github.com/Dreamacro/clash/tunnel.tunnel.HandleTCPConn({}, {0x1667590?, 0xc00029a008?}, 0xc001806960?)
	github.com/Dreamacro/clash/tunnel/tunnel.go:508 +0x69b
github.com/Dreamacro/clash/tunnel.handleTCPConn({0x165a1b0, 0xc000662060})
	github.com/Dreamacro/clash/tunnel/tunnel.go:682 +0xcc
github.com/Dreamacro/clash/tunnel.retry[...]({0x165dea0?, 0xc000426000}, 0xc00052be88, 0xc00052bde8)
	github.com/Dreamacro/clash/tunnel/tunnel.go:509 +0x8c
github.com/Dreamacro/clash/tunnel.handleTCPConn.func3({0x165dea0?, 0xc000426000?})
	github.com/Dreamacro/clash/adapter/adapter.go:67 +0x2a
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0x7f13b01749d8?, {0x165dea0?, 0xc000426000?}, 0x20b8a40?, {0x0?, 0xc00024da20?, 0x410545?})
	github.com/Dreamacro/clash/adapter/outboundgroup/selector.go:22 +0xb3
github.com/Dreamacro/clash/adapter/outboundgroup.(*Selector).DialContext(0xc000466200, {0x165dea0, 0xc000426000}, 0x410545?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/adapter.go:67 +0x2a
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc0001b3b00?, {0x165dea0?, 0xc000426000?}, 0x424d45?, {0x0?, 0xc0006621c0?, 0xc00024d958?})
	github.com/Dreamacro/clash/adapter/outboundgroup/selector.go:22 +0xb3
github.com/Dreamacro/clash/adapter/outboundgroup.(*Selector).DialContext(0xc0004449e0, {0x165dea0, 0xc000426000}, 0x2?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/adapter.go:67 +0x2a
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc0001b3500?, {0x165dea0?, 0xc000426000?}, 0xc00024d890?, {0x0?, 0xc0006621c0?, 0x20?})
	github.com/Dreamacro/clash/adapter/outboundgroup/urltest.go:64 +0xbe
github.com/Dreamacro/clash/adapter/outboundgroup.(*URLTest).DialContext(0xc0001b34a0, {0x165dea0, 0xc000426000}, 0x0?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/adapter.go:67 +0x2a
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc0001b3440?, {0x165dea0?, 0xc000426000?}, 0xc00024d7c0?, {0x0?, 0xc000662180?, 0xc00024d828?})
	github.com/Dreamacro/clash/adapter/outbound/trojan.go:122 +0x1ff
github.com/Dreamacro/clash/adapter/outbound.(*Trojan).DialContext(0xc0003ad7c0, {0x165dea0, 0xc000426000}, 0xc0007e72f0?, {0x0?, 0x3?, 0xc0001b34a0?})
	github.com/Dreamacro/clash/adapter/outbound/trojan.go:143 +0x24b
github.com/Dreamacro/clash/adapter/outbound.(*Trojan).DialContextWithDialer(0xc0003ad7c0, {0x165dea0, 0xc000426000}, {0x1652b60?, 0xc000480cc0?}, 0xf46b7f?)
	github.com/Dreamacro/clash/adapter/outbound/trojan.go:91 +0xcf
github.com/Dreamacro/clash/adapter/outbound.(*Trojan).StreamConnContext(0xc0003ad7c0, {0x165dea0?, 0xc000426000?}, {0x1668120?, 0xc0001b1dc0?}, 0xc0002ad7a0)
	github.com/Dreamacro/clash/adapter/outbound/trojan.go:74 +0x1e9
github.com/Dreamacro/clash/adapter/outbound.(*Trojan).plainStream(0xc0003ad7c0, {0x165dea0, 0xc000426000}, {0x1668120, 0xc0001b1dc0})
	github.com/Dreamacro/clash/transport/trojan/trojan.go:131 +0x228
github.com/Dreamacro/clash/transport/trojan.(*Trojan).StreamWebsocketConn(0xc0001c7ae0, {0x165dea0, 0xc000426000}, {0x1668120, 0xc0001b1dc0}, 0xc00024d3d0)
	github.com/Dreamacro/clash/transport/vmess/websocket.go:476 +0x1d7
github.com/Dreamacro/clash/transport/vmess.StreamWebsocketConn({0x165dea0, 0xc000426000}, {0x1668120, 0xc0001b1dc0}, 0xc00028c680)
	github.com/Dreamacro/clash/transport/vmess/websocket.go:374 +0x907
github.com/Dreamacro/clash/transport/vmess.streamWebsocketConn({0x165dea0, 0xc000426000}, {0x1668120, 0xc0001b1dc0}, 0xc00028c680, 0x0)
	net/http/header.go:40
net/http.Header.Set(...)
	net/textproto/header.go:22
net/textproto.MIMEHeader.Set(...)
goroutine 183 [running]:
panic: assignment to entry in nil map
```

### OpenClash Config

```shell
使用lhie1一键生成配置，meta核心FakeIP增强模式，三个服务器（trojan+ssr+ssr）其它没有特别的配置
```

### Expected Behavior

正常启动并工作

**Comment by Hansen1018** [comment]
我也是相同问题

**Comment by iuiiuiiiu** [comment]
Meta+TUN，直接不能上网。Redir可以。

**Comment by Joee-D** [comment]
最新的meta核心是有问题，升级完后vmess-ws-tls节点无法连接，服务器配置没有任何变化，服务端报302。
手动恢复到之前的核心是ok的，目前已暂时回退到官方最后的稳定release v1.16.0。

**Comment by zlwu** [comment]
meta核心没人维护了，这个问题提到这里其实有点不合适，后续咋办捏😭😭😭

**Comment by minisind** [comment]
直接从这个项目中找的META内核感觉 有BUG.  GITHUB上有另一个可以使用的内核。 文件大了很多。
![newCore](https://github.com/vernesong/OpenClash/assets/133642682/ef4bd9ee-6d5a-4de8-9c6b-9deee49b0898)
顺便说一句，难怪最近魔法网络快了很多，原来很多人爬不上来了。

**Comment by keay250** [comment]
> 直接从这个项目中找的META内核感觉 有BUG. GITHUB上有另一个可以使用的内核。 文件大了很多。 ![newCore](https://user-images.githubusercontent.com/133642682/284778203-ef4bd9ee-6d5a-4de8-9c6b-9deee49b0898.jpg) 顺便说一句，难怪最近魔法网络快了很多，原来很多人爬不上来了。

这个应该是原始的完整meta内核,自然大一些

**Comment by Joee-D** [comment]
> > 直接从这个项目中找的META内核感觉 有BUG. GITHUB上有另一个可以使用的内核。 文件大了很多。 ![newCore](https://user-images.githubusercontent.com/133642682/284778203-ef4bd9ee-6d5a-4de8-9c6b-9deee49b0898.jpg) 顺便说一句，难怪最近魔法网络快了很多，原来很多人爬不上来了。
> 
> 这个应该是原始的完整meta内核,自然大一些

openclash库上的应该是用UPX压缩过的，可以拿官方的自己压缩，也可以去shellclash库上面取
https://github.com/juewuy/ShellCrash/tree/master/bin/clash.meta

**Comment by minisind** [comment]
You're the best

**Comment by mwnu** [comment]
> Meta+TUN，直接不能上网。Redir可以。

试了，用shellclash的内核还是不行，一切换到meta就崩溃。

**Comment by zlwu** [comment]
> > Meta+TUN，直接不能上网。Redir可以。
> 
> 试了，用shellclash的内核还是不行，一切换到meta就崩溃。

你试一下版本g3a9fc39的内核，我这儿是可以的
https://github.com/vernesong/OpenClash/commit/2af8f1070e6a5b4f8127421a276d9b23b4d378f5

**Comment by mwnu** [comment]
> > > Meta+TUN，直接不能上网。Redir可以。
> > 
> > 
> > 试了，用shellclash的内核还是不行，一切换到meta就崩溃。
> 
> 你试一下版本g3a9fc39的内核，我这儿是可以的 [2af8f10](https://github.com/vernesong/OpenClash/commit/2af8f1070e6a5b4f8127421a276d9b23b4d378f5)

没有ARMv8的内核，不知道下哪个

**Comment by mwnu** [comment]
> ARMv8 就是选ARM64啊。V8 64位的。

还是会崩溃，看来不是内核的问题/

**Comment by zlwu** [comment]
meta升级到alpha-gcc64297之后问题解决
