### ISSUE TITLE
tun 内核无法启动

### ISSUE THREAD

**Issue by de-conf** [vernesong/OpenClash#961]
tun 版本 
---
2020.10.29.g5e54f48
---

请问tun历史版本下载地址在哪里？找不到，回退不了！ 另外，该issue应该在这里提出,还是在 ` Dreamacro/clash ` 下提出？

``` 
	github.com/Dreamacro/clash/tunnel/tunnel.go:134 +0xac
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:350 +0x490
github.com/Dreamacro/clash/tunnel.handleTCPConn(0x798688, 0x1426970)
	github.com/Dreamacro/clash/tunnel/connection.go:131
github.com/Dreamacro/clash/tunnel.handleSocket(...)
	github.com/Dreamacro/clash/tunnel/connection.go:147 +0x11c
github.com/Dreamacro/clash/tunnel.relay(0xa6cb0840, 0x1426970, 0xa6cb0810, 0x1426a80)
	io/io.go:382 +0x5c
io.CopyBuffer(0xa6cb0870, 0x1426a80, 0xa6cb0888, 0x1426970, 0x12b8000, 0x5000, 0x8000, 0x1, 0x19fbc, 0xb0ad8c, ...)
	io/io.go:411 +0x1b0
io.copyBuffer(0xa6cb0870, 0x1426a80, 0xa6cb0888, 0x1426970, 0x12b8000, 0x5000, 0x8000, 0x6248f8, 0x684178, 0x5f1c00, ...)
	github.com/Dreamacro/clash/tunnel/tracker.go:50 +0xa0
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Write(0x1426a80, 0x12b8000, 0x219, 0x8000, 0x219, 0x0, 0x0)
goroutine 98 [running]:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11ff4]
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by changsoul** [comment]
Dreamacro/clash的内核没问题，正常使用。https://github.com/Dreamacro/clash/releases/tag/premium 这里下载对应版本，改名为clash_tun，chmod +x clash_tun加执行权限。虽然大了点，但是用着放心，原码公开！

**Comment by yaling888** [comment]
Dreamacro/clash的内核没问题，正常使用。https://github.com/Dreamacro/clash/releases/tag/premium 这里下载对应版本，改名为clash_tun，chmod +x clash_tun加执行权限。虽然文件大了点，但是用着放心，原码公开！

**Comment by de-conf** [comment]
> Dreamacro/clash的内核没问题，正常使用。https://github.com/Dreamacro/clash/releases/tag/premium 这里下载对应版本，改名为clash_tun，chmod +x clash_tun加执行权限。虽然文件大了点，但是用着放心，原码公开！

```
你看wiki页面  闭源 and free
