### ISSUE TITLE
OpenClash无法启动

### ISSUE THREAD

**Issue by morytyann** [vernesong/OpenClash#967]
OpenClash 调试日志

生成时间: 2020-11-09 14:43:35
插件版本: v0.40.15-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#
主机型号: VMware, Inc. VMware Virtual Platform
固件版本: OpenWrt 19.07.4 r11208-ce6496d796
LuCI版本: git-20.310.50568-7b1b82d-1
内核版本: 4.14.195
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
iptables-mod-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.10.29.g5e54f48
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-219-g9ac38a4
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.2.0-14-g87e4d94
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/fkwall.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 117.50.10.10
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5
    - 223.6.6.6
  Auto:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
    

#===================== 防火墙设置 =====================#

#NAT chain

# Generated by iptables-save v1.8.3 on Mon Nov  9 14:43:35 2020
*nat
:PREROUTING ACCEPT [1324:280663]
:INPUT ACCEPT [477:77620]
:OUTPUT ACCEPT [220:16268]
:POSTROUTING ACCEPT [14:2339]
:MINIUPNPD - [0:0]
:MINIUPNPD-POSTROUTING - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i pppoe-Wan -m comment --comment "!fw3" -j zone_wan_prerouting
-A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A POSTROUTING -o pppoe-Wan -m comment --comment "!fw3" -j zone_wan_postrouting
-A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
-A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
-A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
-A zone_wan_postrouting -j MINIUPNPD-POSTROUTING
-A zone_wan_postrouting -m comment --comment "!fw3" -j MASQUERADE
-A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
-A zone_wan_prerouting -j MINIUPNPD
COMMIT
# Completed on Mon Nov  9 14:43:35 2020

#Mangle chain

# Generated by iptables-save v1.8.3 on Mon Nov  9 14:43:35 2020
*mangle
:PREROUTING ACCEPT [361137:379218917]
:INPUT ACCEPT [13797:4394826]
:FORWARD ACCEPT [347078:374654815]
:OUTPUT ACCEPT [4973:6432749]
:POSTROUTING ACCEPT [351840:381078103]
-A FORWARD -o pppoe-Wan -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A FORWARD -i pppoe-Wan -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
COMMIT
# Completed on Mon Nov  9 14:43:35 2020

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         *.78.156.1     0.0.0.0         UG    0      0        0 pppoe-Wan
*.78.156.1     0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-Wan
172.16.0.0      0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via *.78.156.1 dev pppoe-Wan proto static 
*.78.156.1 dev pppoe-Wan proto kernel scope link src 39.78.156.40 
172.16.0.0/24 dev br-lan proto kernel scope link src 172.16.0.1 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 61.135.169.121
Address 2: 61.135.185.32
www.baidu.com	canonical name = www.a.shifen.com

#===================== resolv.conf.auto =====================#
# Interface Wan
nameserver *.102.128.68
nameserver *.102.134.68

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Mon, 09 Nov 2020 06:43:35 GMT
Etag: "575e1f5d-115"
Last-Modified: Mon, 13 Jun 2016 02:50:05 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#

panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0xd2dcc0, 0xb1c4e0)
	reflect/value.go:1894 +0x189
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeString(0xc000063638, 0xc0001fa060, 0xa, 0x0, 0x0, 0xb1c4e0, 0xc000117a30, 0x198, 0x2, 0xa)
	github.com/Dreamacro/clash/common/structure/structure.go:120 +0x14a
github.com/Dreamacro/clash/common/structure.(*Decoder).decode(0xc000063638, 0xc0001fa060, 0xa, 0x0, 0x0, 0xb1c4e0, 0xc000117a30, 0x198, 0x97, 0x0)
	github.com/Dreamacro/clash/common/structure/structure.go:70 +0x514
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeSlice(0xc000063638, 0xaec481, 0x7, 0xb0fa20, 0xc000182c40, 0xb10ba0, 0xc0001d5830, 0x197, 0xc0001e2c88, 0x1)
	github.com/Dreamacro/clash/common/structure/structure.go:161 +0x3b9
github.com/Dreamacro/clash/common/structure.(*Decoder).decode(0xc000063638, 0xaec481, 0x7, 0xb0fa20, 0xc000182c40, 0xb10ba0, 0xc0001d5830, 0x197, 0x2, 0x19)
	github.com/Dreamacro/clash/common/structure/structure.go:74 +0x372
github.com/Dreamacro/clash/common/structure.(*Decoder).Decode(0xc000063638, 0xc0001e0840, 0xafb220, 0xc0001d5810, 0xc0000637d8, 0x0)
	github.com/Dreamacro/clash/common/structure/structure.go:57 +0x4da
github.com/Dreamacro/clash/config.proxyGroupsDagSort(0xc0001d56c0, 0xd, 0xd, 0x4, 0xc0001e3948)
	github.com/Dreamacro/clash/config/utils.go:32 +0x17b
github.com/Dreamacro/clash/config.parseProxies(0xc000125440, 0xc00012c580, 0x0, 0x0, 0xafc0a0)
	github.com/Dreamacro/clash/config/config.go:347 +0xa7d
github.com/Dreamacro/clash/config.ParseRawConfig(0xc000125440, 0x4541, 0x4741, 0xc000125440)
	github.com/Dreamacro/clash/config/config.go:231 +0xc5
github.com/Dreamacro/clash/config.Parse(0xc000022800, 0x4541, 0x4741, 0x4541, 0x4741, 0x0)
	github.com/Dreamacro/clash/config/config.go:179 +0x7f
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
	github.com/Dreamacro/clash/hub/executor/executor.go:60
github.com/Dreamacro/clash/hub/executor.ParseWithPath(0x7fff37d1bb84, 0x21, 0x98, 0x98, 0xc00011f9a0)
	github.com/Dreamacro/clash/hub/executor/executor.go:55 +0x87
github.com/Dreamacro/clash/hub/executor.Parse(...)
	github.com/Dreamacro/clash/hub/executor/executor.go:45
github.com/Dreamacro/clash/hub.Parse(0x0, 0x0, 0x0, 0x6, 0x116f7a0)
	github.com/Dreamacro/clash/hub/hub.go:31 +0x3f
main.main()
	github.com/Dreamacro/clash/main.go:96 +0x3c8
2020-11-09 14:42:16 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
2020-11-09 14:42:16 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File

```

**Comment by morytyann** [comment]
已尝试重装libcap/libcap-bin、luci-app-openclash均无效，capsh输出正常

**Comment by LarkinZero** [comment]
我也遇到这个问题了，请问是如何解决的呢
